# Generated by Django 5.0.6 on 2024-08-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=128)),
                ('mobile', models.CharField(blank=True, default='Not specified', max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Not specified', max_length=10)),
                ('mother_tongue', models.CharField(default='Not specified', max_length=50)),
                ('religion', models.CharField(default='Not specified', max_length=50)),
                ('caste', models.CharField(default='Not specified', max_length=100)),
                ('marriage_status', models.CharField(default='Not specified', max_length=15)),
                ('height', models.CharField(default='Not specified', max_length=10)),
                ('horoscope', models.CharField(default='Not specified', max_length=50)),
                ('country', models.CharField(default='Not specified', max_length=50)),
                ('state', models.CharField(default='Not specified', max_length=50)),
                ('city', models.CharField(default='Not specified', max_length=100)),
                ('degree', models.CharField(default='Not specified', max_length=50)),
                ('employed_in', models.CharField(default='Not specified', max_length=50)),
                ('occupation', models.CharField(default='Not specified', max_length=50)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('career_about', models.TextField(default='')),
                ('family_type', models.CharField(default='Not specified', max_length=15)),
                ('father_occupation', models.CharField(default='Not specified', max_length=50)),
                ('mother_occupation', models.CharField(default='Not specified', max_length=50)),
                ('brother_count', models.IntegerField(default=0)),
                ('family_living_in', models.CharField(default='Not specified', max_length=100)),
                ('contact_address', models.TextField(default='Not specified')),
                ('about_family', models.TextField(blank=True, default='')),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pictures/')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='chat.roles')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
                'ordering': ['name'],
            },
        ),
    ]
